### ISSUE TITLE
Child Psychiatrist's wish list for Child Welfare Digital Services

### ISSUE THREAD

**Issue by dakinibean** [CDTgithub/DigitalServiceOpportunities#1]
Hi!  I am not a Californian, but I do work in Child Welfare, and if I can be helpful in this project, I would love to be.  On of my roles in my community is child psychiatrist.  My patients are often living in poverty, and their psychiatric problems are frequently entangled with social issues that could be better addressed through thoughtful implementation of technology.  For example, the people bring children to my office who are having trouble focusing in school, and it is not rare to learn that they are hungry, and their families are overwhelmed with stressors.  Worse yet, despite the range and depth of google searches, their families aren't aware of available local resources for help.  For example, I met a family who moved to town to take space from an abusive relationship, living two blocks from the rec center, whose daughter was brought to my office for annoying people by roller skating up and down the hallway of her apartment complex.  Locals all know about the rec center, but this family wasn't local.  There are a few programs through which this family could use the center for free, but they are pretty hard to keep track of, and a centralized, family-friendly, resource guide could be life-changing, especially in a rural town that doesn't have free newspapers describing family-friendly events.  If such a resource guide could coordinate with calendars, it could help overwhelmed families keep track of things.  Given that smart phones have replaced other forms of community for my patient population, I'd love to maximize their utility.  Crowd-sourcing and machine learning could help target supports, as well as address  social issues that my patients struggle with.  This would also help the psychiatrist and rural physician shortage -- if I spend huge portions of my day addressing housing insecurity, job insecurity, and food insecurity, I am not able to focus on actual mental illness.   Lastly, many of my patients need is IRL connection, and meaning.  I can facilitate that in my office, but technology could definitely do it better.  Facilitating social infrastructure to bring people together for things like swimming, cooking classes, or even walks can help bridge socio-economic and cultural divides that are becoming increasingly problematic.  

Please let me know if I can help.  In case more background would be useful, below is an article I wrote to clarify how technology could help child psychiatry be more effective, efficient, and humane.

https://medium.com/@sophia.kuo/how-to-keep-your-psychiatrist-from-throwing-meds-at-your-problems-9a9584a38f91#.2bqgtrkh2

**Comment by danhon** [comment]
Thanks for your comments about Child Welfare, Sophia. The Child Welfare Digital Service will be starting work on case management soon, and it sounds like as a psychiatrist you'd also be involved in using the system. You can follow along with the team's progress when they start on case management at their open [dashboard](https://cwds.ca.gov/dashboard/digitalservices.html).

**Comment by RonHarden** [comment]
Hope this will be focused since face to face treatment for now is risky. 

Just like what they always say, "Always seek immediate help if a child engages in unsafe behavior or talks about wanting to hurt him or herself or someone else".

Ron Harden
https://www.cnscenteraz.com/
