### ISSUE TITLE
CCWDS Scrum Coach

### ISSUE THREAD

**Issue by adampotter** [CDTgithub/DigitalServiceOpportunities#2]
Hey, 

Looks like some really interesting jobs!

I have a few questions in regards to the CCWDS Scrum Coach role:

- Is there a closing date for applications or is it more of an open ended recruitment?
- Are you in a position to offer roles to UK nationals? 

Thanks, 
Adam

**Comment by CDTProcurement** [comment]
Adam,

Thanks for your interest in the Scrum Coach role. 

Currently this is an open-ended recruitment open to people with authorization to work in the United States.
