### ISSUE TITLE
Summer Internships for Graduate Students

### ISSUE THREAD

**Issue by namimody** [CDTgithub/DigitalServiceOpportunities#5]
Hi! I was wondering if there might be opportunities for graduate students to work with this team as part of a summer internship. (Personally, I have both product management and policy experience/interests.) 

Thanks so much!

**Comment by CDTProcurement** [comment]
We are always on the lookout for interns dedicated to public service. If you are interested, please send us your resume and a writing sample (<2000 words) that demonstrates your ability to communicate a complex topic to a general audience.

**Comment by namimody** [comment]
Thank you! I will email Adrian Farley.
