### ISSUE TITLE
Applying for User Researcher

### ISSUE THREAD

**Issue by TF-FT** [CDTgithub/DigitalServiceOpportunities#8]
Hi There,

I'm wondering if sending Adrian Farley with my information is enough to apply for this position, or if I should sign up on the jobs.ca.gov site.

Thanks!

**Comment by elfox** [comment]
I'm also curious! I signed up on jobs.ca.gov and got scared off by the Software Systems Specialist required exam to apply to the UX positions listed there. The sample test questions look heavily weighted toward developers. I'm not sure I could pass as a researcher or designer. How should I handle this? I'm emailing Adrian regardless!

**Comment by CDTProcurement** [comment]
Please just send an email to Adrian
